version: '2.1'

services:
  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3
    
  backend:
    image: veritus/backend:latest
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - SECRET_KEY=$SECRET_KEY
      - DB_HOST=db
    command: python3 src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    image: veritus/frontend:latest
    volumes:
      - /code/build
  
  nginx:
    image: nginx:alpine
    links:
      - frontend
    volumes_from:
      - frontend:ro
    volumes:
      - ./nginx/conf.d/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80