version: '3'

services:
  db:
    image: postgres:9.6.3
    environment:
    - POSTGRES_PASSWORD=${DB_PASS}
    
  backend:
    image: arihrannar/veritus-backend:latest
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    command: python3 src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
